name: Release Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target_type:
          - server
          - client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Cache xmake packages
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Update repositories
        run: xmake repo -u

      - name: Configure project
        run: xmake f -a x64 -m release -p windows --target_type=${{ matrix.target_type }} -y

      - name: Build project
        run: xmake -w -y

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ matrix.target_type }}-windows-x64
          path: bin/

  update-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v3

      - name: Update release body
        uses: softprops/action-gh-release@v3
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    strategy:
      matrix:
        target_type:
          - server
          - client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ matrix.target_type }}-windows-x64
          path: artifact

      - name: Copy additional files
        run: |
          cp CHANGELOG.md LICENSE README.md artifact/ || true

      - name: Archive release
        run: |
          cd artifact
          zip -r ../${{ github.event.repository.name }}-windows-${{ matrix.target_type }}-x64.zip .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ github.event.repository.name }}-windows-${{ matrix.target_type }}-x64.zip
